name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cache_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache-and-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn lint

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
        nock-version: [ 11.x, 12.x, 13.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn add nock@${{ matrix.nock-version }}
      - run: yarn test:unit:coverage
      - run: yarn test:int
      - name: Node ${{ matrix.node-version }} / Nock ${{ matrix.nock-version }} coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: test-${{ matrix.node-version }}-${{ matrix.nock-version }}
          parallel: true

  coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn lint
