name: release

on:
  push:
    tags:
      - 'release-v**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: Get version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/release-v}
      - run: |
          yarn install
          yarn version ${{ steps.get-version.output.VERSION }}
          yarn conventional-changelog -p conventionalcommits -i CHANGELOG.md -s
          git config user.email "smuggler@bots.ekino.com"
          git config user.name "Smuggler Bot"
          git add CHANGELOG.md package.json
          git commit -m "chore(version-bump): ${{ steps.get-version.output.VERSION }}"
          git push
          git tag ${{ steps.get-version.output.VERSION }}
          git push --set-upstream origin ${{ steps.get-version.output.VERSION }}
          zip sources.zip ./*
          zip ekino-smuggler-${{ steps.get-version.output.VERSION }}.zip build package.json README.md
      - name: Build & publish to NPM
        run: |
          yarn compile
          yarn npm publish --tag ${{ steps.get-version.output.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release version ${{ steps.get-version.output.VERSION }}
        id: release-version
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.output.VERSION }}
          release_name: V${{ steps.get-version.output.VERSION }}
      - name: Upload sources release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-version.outputs.upload_url }}
          asset_path: ./sources.zip
          asset_name: sources.zip
          asset_content_type: application/zip
      - name: Upload library release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-version.outputs.upload_url }}
          asset_path: ./ekino-smuggler-${{ steps.get-version.output.VERSION }}.zip
          asset_name: ekino-smuggler-${{ steps.get-version.output.VERSION }}.zip
          asset_content_type: application/zip
